baseURL = "https://candid-beignet-c56fdd.netlify.app/"
languageCode = "en-us"
title = "DnD Base"
theme = "schmopera"

[taxonomies]
  category = "categories"

[permalinks]
  articles = "/:slug"

[related]
  includeNewer = true

[[related.indices]]
  name = "author"
  toLower = true
  weight = 100.0

[[related.indices]]
  name = "related_people"
  toLower = true
  weight = 100.0

[[related.indices]]
  name = "related_companies"
  toLower = true
  weight = 100.0
